{ config, pkgs, ... }:

{
  ## ─────────────────────────────────────────────────────────────
  ## Filesystem Mounts
  ## ─────────────────────────────────────────────────────────────

  ## Mount A HDD to "/mnt/other"
  fileSystems."/mnt/other" = {
    device = "/dev/disk/by-uuid/XXXXXXXXXXXXXXXX";  ## UUID of the device.
    fsType = "ntfs";                                ## Filesystem type (NTFS, for compatibility with Windows)
    options = [ "defaults" "nofail" ];
    ## "defaults" ~ uses default mount options for this filesystem
    ## "nofail" ~ allows the system to boot even if the mount fails
  };

  ## Mount A HDD to "/mnt/games"
  fileSystems."/mnt/games" = {
    device = "/dev/disk/by-uuid/XXXXXXXXXXXXXXXX"; ## UUID of the device.
    fsType = "ntfs";                               ## Filesystem type (NTFS, for compatibility with Windows)
    options = [ "defaults" "nofail" ];             ## Default mount options with nofail
  };

  ## Mount A HDD to "/mnt/codes"
  fileSystems."/mnt/codes" = {
    device = "/dev/disk/by-uuid/XXXXXXXXXXXXXXXX"; ## UUID of the device.
    fsType = "ntfs";                               ## Filesystem type (NTFS, for compatibility with Windows)
    options = [ "defaults" "nofail" ];             ## Default mount options with nofail
  };

  ## Mount A USB to "/mnt/backup"
  fileSystems."/mnt/backup" = {
    device = "/dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"; ## UUID of the device.
    fsType = "ext4";                               ## ext4 filesystem
    options = [ "defaults" "nofail" ];             ## Default mount options with nofail
  };
}

## NOTE:
##   the partition for "/mnt/shared" is imported in  "hardware-configuration.nix" which is auto generated by nixos.
##   the "shared" partition is for linked downloads/settings/games/documents on both nixos and ubuntu partition.